name: waffly
description: The new latin american unicorn.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.0
  font_awesome_flutter: ^8.10.0
  provider: ^4.3.2+2
  animated_text_kit: ^2.5.4
  animate_do: ^1.7.3
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  lint: ^1.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/data/
