name: ed_project
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.0
  font_awesome_flutter: ^8.8.1
  provider: ^4.3.2+2
  animated_text_kit: ^2.2.0
  animate_do: ^1.7.3
  firebase: ^7.3.0
  firebase_core: ^0.5.0
  firebase_analytics: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
